version: '3'
services:
  json-server:
    image: node
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    working_dir: /data
    command: bash -c "npm install -g json-server && json-server --watch /data/db.json --host 0.0.0.0"
