version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/app/static:ro
    depends_on:
      - lite-server
      - json-server

  lite-server:
    image: node
    volumes:
      - ./app:/app/static
    working_dir: /app
    command: bash -c "npm install lite-server && npx lite-server --no-open"
    deploy:
      replicas: 3

  json-server:
    image: node
    volumes:
      - ./data:/data
    working_dir: /data
    command: bash -c "npm install -g json-server && json-server --watch /data/db.json --host 0.0.0.0"
    deploy:
      replicas: 3

