version: '3.3'
services:
  lite-server:
    image: node
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    command: bash -c "npm install lite-server && npx lite-server --no-open"
